### ISSUE TITLE
RE: How do I run Azure powershell commands?

### ISSUE THREAD

**Issue by stuartjdavies** [fsprojects/FSharp.Management#47]
Hi,

How do I run Azure powershell commands?

Below is my script:

```fsharp
#r "../packages/FSharp.Management.0.1.1/lib/net40/FSharp.Management.dll"
#r "../packages/FSharp.Management.0.1.1/lib/net40/FSharp.Management.PowerShell.dll"
#r "System.Management.Automation"
#r "Microsoft.Management.Infrastructure"

open FSharp.Management
open Microsoft.PowerShell

type PS = PowerShellProvider< PSSnapIns="WDeploySnapin3.0", Is64BitRequired=false>
PowerShellProvider.Runtime

PS.``Set-ExecutionPolicy``(executionPolicy=ExecutionPolicy.RemoteSigned) 
PS.``Import-Module``(name=[|"Azure"|])
```

Some initialization...

```fsharp
// Ideal execution which doesn't seem to work
PS.``Add-AzureAccount``(  some params ... )
```

See "http://azure.microsoft.com/en-us/documentation/articles/install-configure-powershell/"
for more examples 

How do I run commands from the Azure module?

In my opinion this would be an awesome feature for F# I think because it would open up many possibilities.

Regards
Stuart Davies

**Comment by dsyme** [comment]
Ping @forki @vasily-kirichenko @sergey-tihon @dtchepak  We should answer this :)

@stuartjdavies - did you find a solution for this?

**Comment by vasily-kirichenko** [comment]
Sorry, I try To stay away from both PS and Azure.

**Comment by sergey-tihon** [comment]
@stuartjdavies sorry, i missed this question.

As I understand, it is not possible right now.
In order to get intellisense over Azure commands TP should load it before type inference.
So, it sounds like we should add new parameter to PowershellProvider.

**Comment by stuartjdavies** [comment]
No, I didn't find a solution. It was I while since I looked at this but by memory I don't think it works for any package you want to load. Not just the azure package. If this is the case it might be a good feature to add. Anyway, there may better things to spend time on.

**Comment by ChristopherBuller** [comment]
I worked thru creating this exact feature before, The module cmdlets don't list with RunspaceConfiguration.Cmdlets so they are missing. A module cmdlet list can be piped into PSRuntimeHosted instance in the cmdlets member to fix the missing cmdlets.

I think I created an new constructor PSRuntimeHosted(snapIns:string[], modules:[])

I forget where I got stuck but the root issue is RunspaceConfiguration.Cmdlets don't list the module commands so they have to be added to the provider with additional effort.
2 solutions I worked toward 
are implementing a new list of CmdletConfigurationEntry rather than the RunspaceConfigurationCmdletEntryCollection that drives the provided commands or

Providing Modules side by side with Snap Ins, Enumerating each snapIn and Adding them and Enumerating each module and adding them

If interested I can hunt up the code and see where I got stuck, hopefully it's not too far off from the feature

**Comment by sergey-tihon** [comment]
Please try [latest package from NuGet](https://www.nuget.org/packages/FSharp.Management/0.2.1)
```fsharp
type PS = PowerShellProvider< "Azure" >
```
![image](https://cloud.githubusercontent.com/assets/1197905/8637323/72fc5862-2894-11e5-8227-2d9ed8a76c89.png)

**Comment by sergey-tihon** [comment]
Please test it and reopen this issue if needed
